language: java

sudo: true

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="gradlew run"
        - CMD=""
        - COVERAGE_CMD=""
        - DEPLOY="false"