language: java

sudo: true

before_cache:
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
cache:
  directories:
    - .gradle/caches/
    - .gradle/wrapper/

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="gradlew run"
        - CMD="gradlew run"
        - COVERAGE_CMD=""
        - DEPLOY="false"